---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: false

platforms:
  - name: cumulus-vx-2.5.3
    driver:
      box: cumulus-vx-2.5.3
      box_url: 'https://networking.objects-us-east-1.dream.io/vagrant/boxes/cumulus-vx-2.5.3-chef-vbox.box'
      provision: true
      vagrantfiles: ['test/provision_chef.rb']
  - name: cumulus-vx-3.3.2
    driver:
      box: cumulus-vx-3.3.2
      box_url: 'http://cumulusfiles.s3.amazonaws.com/cumulus-linux-3.3.2-vx-amd64.box'
      provision: true
      vagrantfiles: ['test/provision_chef_cl3.rb']

suites:
  - name: default
    run_list:
      - recipe[cumulus-switch-test]
