Metrics/LineLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Style/RedundantBegin:
  Enabled: false
Style/RegexpLiteral:
  Enabled: false
